//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_campana
    {
        public int pk_campana { get; set; }
        public string nombre_campana { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> fk_tienda { get; set; }
        public Nullable<int> fk_solicitud_campana { get; set; }
        public string tipo_campana { get; set; }
    
        public virtual t_solicitud_campana t_solicitud_campana { get; set; }
        public virtual t_tienda t_tienda { get; set; }
    }
}
