//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_contrato
    {
        public int pk_contrato { get; set; }
        public Nullable<System.DateTime> fecha_contrato { get; set; }
        public Nullable<System.DateTime> fecha_firma { get; set; }
        public Nullable<int> fk_cuenta { get; set; }
        public string condiciones { get; set; }
    }
}
