//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_detalle_ticket_canje
    {
        public int id_ticket_canje { get; set; }
        public int id_modalidad_canje { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> subtotal_puntos { get; set; }
        public Nullable<decimal> subtotal_importe { get; set; }
    
        public virtual t_modalidad_canje t_modalidad_canje { get; set; }
        public virtual t_ticket_canje t_ticket_canje { get; set; }
    }
}
