//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ficha_afiliacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_ficha_afiliacion()
        {
            this.t_cuenta = new HashSet<t_cuenta>();
            this.t_solicitud_atencion = new HashSet<t_solicitud_atencion>();
        }
    
        public int pk_ficha_afiliacion { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string nombre { get; set; }
        public string numero_documento { get; set; }
        public string sexo { get; set; }
        public string correo { get; set; }
        public string numero_telefono { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string estado_afiliado { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> fk_tipo_documento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_cuenta> t_cuenta { get; set; }
        public virtual t_tipo_documento t_tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_solicitud_atencion> t_solicitud_atencion { get; set; }
    }
}
