//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_producto_canje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_producto_canje()
        {
            this.t_reporte_stock_producto_canje = new HashSet<t_reporte_stock_producto_canje>();
            this.t_ticket_canje = new HashSet<t_ticket_canje>();
        }
    
        public int fk_modalidad { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string stock_producto { get; set; }
        public string condicion { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string categoria_producto { get; set; }
        public int pk_producto_canje { get; set; }
        public string nombre_producto { get; set; }
        public System.DateTime fecha_baja { get; set; }
    
        public virtual t_modalidad_canje t_modalidad_canje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_reporte_stock_producto_canje> t_reporte_stock_producto_canje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ticket_canje> t_ticket_canje { get; set; }
    }
}
