//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_producto_tienda
    {
        public int fk_tienda { get; set; }
        public Nullable<decimal> numero_stock_tienda { get; set; }
        public string flag_estado { get; set; }
    }
}
