//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_solicitud_atencion
    {
        public string pk_solicitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> fk_ficha_afiliacion { get; set; }
        public Nullable<int> fk_tienda { get; set; }
    
        public virtual t_ficha_afiliacion t_ficha_afiliacion { get; set; }
        public virtual t_tienda t_tienda { get; set; }
    }
}
