//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_tarjera_afiliacion_cuenta
    {
        public int id_tarjeta_afiliacion_cuenta { get; set; }
        public Nullable<int> fk_tarjeta_afiliacion { get; set; }
        public Nullable<int> fk_cuenta { get; set; }
        public Nullable<System.DateTime> fecha_afiliacion { get; set; }
        public string estado { get; set; }
    
        public virtual t_cuenta t_cuenta { get; set; }
        public virtual t_tarjeta_afiliacion t_tarjeta_afiliacion { get; set; }
    }
}
