//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ticket_canje
    {
        public int pk_ticket_canje { get; set; }
        public string numero_ticket { get; set; }
        public Nullable<System.DateTime> fecha_ticket { get; set; }
        public string tienda { get; set; }
        public Nullable<decimal> puntos { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> fk_producto_canje { get; set; }
    
        public virtual t_producto_canje t_producto_canje { get; set; }
    }
}
