//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelizacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ticket_transferencia
    {
        public int id_transferencia { get; set; }
        public Nullable<int> puntos_transferidos { get; set; }
        public string numero_ticket { get; set; }
        public Nullable<System.DateTime> fecha_transferencia { get; set; }
        public string motivo_transferencia { get; set; }
        public string cuenta_origen { get; set; }
        public Nullable<int> fk_cuenta { get; set; }
        public string cuenta_destino { get; set; }
    
        public virtual t_cuenta t_cuenta { get; set; }
    }
}
